server:
  port: 7901
spring:
  application:
    name: boxflux-movie
  
logging:
  level:
    root: info
    com.boxflux.micservice: debug
    
eureka:
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
info:
  build:
    artifact: project.artifactId
    name: project.name
    description: project.description
    version: project.version
    